README.md
Cf https://github.com/jenkins-infra/helpdesk/pull/2731#discussion_r785007112
=> chore: remove mention of website and wiki

README.md
Cf https://github.com/jenkins-infra/helpdesk/pull/2731#discussion_r785007803
=> chore: remove mention of the jira issue migration in the README

.github/issues-similarity.yml
Render something like this:
Default value for the threshold and excludes list, will probably need tuning.
=> feat: implement issues-similarity-analysis GHA

workflows/autolabeler
Close https://github.com/jenkins-infra/helpdesk/issues/12
=> feat: auto label issues based on service(s) selected

.github/workflows/autolabels.yaml
=> typo in action name

.github/ISSUE_TEMPLATE/1-report-issue.yml, .github/ISSUE_TEMPLATE/4-crowdin.yml
Depends on https://github.com/jenkins-infra/helpdesk/issues/2918
Additionally, a `crowdin` label needs to be created.
=> Add crowdin project issue template

.github/ISSUE_TEMPLATE/config.yml, README.md
=> chore: index with list of issue type and description

.github/workflows/autonotifer.yaml
Ref: https://github.com/jenschelkopf/issue-label-notification-action/issues/12
=> fix(autonotifier): add token to allow team mentions

.github/workflows/issues-similarity.yml
close https://github.com/actions-cool/issues-similarity-analysis/issues/2
=> ci: ignore issue mentioned

.github/comment-ops.yml
See 
- https://github.com/jenkins-infra/helpdesk/issues/3074
- https://github.com/jenkins-infra/.github/pull/15
- https://github.com/timja/github-comment-ops/releases/tag/v1.3.0
=> Enable all `comment-ops` commands

.github/workflows/infra-meeting-release.yaml
Reverts jenkins-infra/helpdesk#3167
=> Revert "feat: include milestone N+1 potential issues"

.github/workflows/infra-meeting-release.yaml
https://github.com/jenkins-infra/helpdesk/issues/3176
=> Address `set-output` deprecation

README.md
And remove "by yourself" for the metrics requests as they aren't public at the moment. (follow-up of #3186)
=> chore: let simple links at the end of the list

.github/workflows/infra-meeting-release.yaml
I've recently edited the [HackMD template for infra weekly meetings](https://hackmd.io/coVyDuCsSH6Go2Tv6SSMWA?both).
This PR updates the generator to backport part of these changes.
=> Update meeting note draft

.github/workflows/infra-meeting-release.yaml
Reverts jenkins-infra/helpdesk#3325
=> Revert "feat(infra-meeting-notes): set appart 'not planned' issues"

.github/workflows/infra-meeting-release.yaml
=> feat: improvements (TODO, no empty section)

.github/dependabot.yml
as per https://github.com/jenkins-infra/helpdesk/issues/3355
=> feat(github-actions): add dependabot updates

scripts/helpdesk3355-add-dependabot-to-repos/copy-dependabot.sh, scripts/helpdesk3355-add-dependabot-to-repos/dependabot.yml, scripts/helpdesk3355-add-dependabot-to-repos/run-helpdesk3355.sh
Ref: https://github.com/jenkins-infra/helpdesk/issues/3355
=> chore: add multi-gitter scripts used for #3355

scripts/helpdesk3355-add-dependabot-to-repos/copy-dependabot.sh, scripts/helpdesk3355-add-dependabot-to-repos/mv-dependabot.sh, scripts/helpdesk3355-add-dependabot-to-repos/run-fixup-helpdesk3355.sh, scripts/helpdesk3355-add-dependabot-to-repos/run-helpdesk3355.sh
Ref: https://github.com/jenkins-infra/helpdesk/issues/3355
=> fixup: script to move dependabot to the correct folder (#3401

.github/workflows/autolabeler.yaml, .github/workflows/autonotifier.yaml, .github/workflows/infra-meeting-release.yaml, .github/workflows/issues-similarity.yml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
=> chore: pin GitHub actions with their SHA-1 instead of their version number (#3407

.github/workflows/infra-meeting-release.yaml
This PR adds comments around the backlog issues section and the list of assignee(s) for each issue.
=> chore: improve infra meeting notes markdown output

.github/workflows/infra-meeting-release.yaml
=> Revert #3909

.github/ISSUE_TEMPLATE/1-report-issue.yml
=> chore: add `community.jenkins.io` to the issue service select

.github/ISSUE_TEMPLATE/1-report-issue.yml
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
=> chore: add `docs.jenkins.io` service in issue template
